#!/bin/sh

PROJECTNAME=caroube
DIRNAME="${PROJECTNAME}"-doc
INSTDIR=/home/drux/htdocs
BAKDIRNAME="${DIRNAME}-${USER}"

settitle "${PROJECTNAME}"' _C__I__C_[D]_I__' &&
if [ -d "${DIRNAME}" ]
then
    rm -r "${DIRNAME}"
fi  &&
(   mkdir "${DIRNAME}"
    cd "${DIRNAME}"
    # wget http://drux.local/matcalc-doc/html/matcalc.tag
) &&
doxygen "${PROJECTNAME}".dox &&

settitle "${PROJECTNAME}"' _C__I__C__D_[I]_' &&
(
    if [ -e "${DIRNAME}" ]
    then
        if [ -d "${INSTDIR}/${BAKDIRNAME}" ]
        then
    	rm -r "${INSTDIR}/${BAKDIRNAME}"
        fi
    
        mv "${INSTDIR}/${DIRNAME}" "${INSTDIR}/${BAKDIRNAME}" &&
    
        cp -a "${DIRNAME}" "${INSTDIR}/${DIRNAME}" &&
    
        cp -a doxygen/background.png doxygen/disjunkt-2x2-64.gif doxygen/smallcaroube.png "${INSTDIR}/${DIRNAME}/html" &&
    
        chmod -R a+rX,g+w "${INSTDIR}/${DIRNAME}" &&
        chgrp -R bzous "${INSTDIR}/${DIRNAME}" && exit 0
        exit 1
    else
        "${DIRNAME} doesn't exist or was not created, bailing out..."
        exit -1
    fi
) &&
if [ -d "${DIRNAME}" ]
then
    rm -r "${DIRNAME}"
fi && exit 0
echo failed somewhere
exit 1


# $Log: dodoc,v $
# Revision 1.4  2004/02/28 15:31:42  jd
# documentation generation and installation tuned to latest disjunkt standards
#
