#!/bin/sh

./doit &&
echo &&
echo '=====================================================================' &&
echo '               compilation + installation done ... documenting       ' &&
echo '=====================================================================' &&
echo && (

if [ ! "${USERNAME}" ]
then
    echo
    echo could not determine USERNAME variable, halted...
    echo
    echo
    exit 1
fi
chmod a+r *.dox
su "${USERNAME}" -c './dodoc' && exit 0
) && (	repozclean
	su "${USERNAME}" -c 'maketags'
) >& "/tmp/${USERNAME}.repozclean.logs" && exit 0
echo failed somewhere...................................................
echo "silently cleaning anyway with repozclean (logs are in /tmp/${USERNAME}.repozclean.logs)"
(   su "${USERNAME}" -c 'repozclean'
    su "${USERNAME}" -c 'maketags'
) >& "/tmp/${USERNAME}.repozclean.logs"
echo repozclean done.
exit 1
# su "${USERNAME}" -c 'configure-jd --prefix=/usr' &&
# su "${USERNAME}" -c maketags
# echo &&
# echo '=====================================================================' &&
# echo '               installation + cleaning done ...                      ' &&
# echo '=====================================================================' &&
# echo &&
# settitle 'caroube _C__I__C_[D]_I__' &&
# rm -rf caroube-doc
# su "${USERNAME}" -c 'doxygen caroube.dox'
# settitle 'caroube _C__I__C__D_[I]_' &&
# su "${USERNAME}" -c 'rm -rf /home/drux/htdocs/caroube-doc-bak'
# su "${USERNAME}" -c 'mv /home/drux/htdocs/caroube-doc /home/drux/htdocs/caroube-doc-bak'
# su "${USERNAME}" -c 'mv caroube-doc /home/drux/htdocs/caroube-doc'
# su "${USERNAME}" -c 'cp doxygen/background.png /home/drux/htdocs/caroube-doc/html'
# su "${USERNAME}" -c 'chmod -R a+rX,g+rw /home/drux/htdocs/caroube-doc'

